workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
    scripts:
      - flutter clean
      - flutter pub get
      - flutter build apk --release --android-skip-build-dependency-validation
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
